#!/bin/bash
sudo su
apt-get install --no-install-recommends xorg
apt-get install --no-install-recommends i3
#apt-get install --no-install-recommends nvidia-331
apt-get install --no-install-recommends rxvt-unicode
apt-get install --no-install-recommends vim
apt-get install --no-install-recommends xautolock
apt-get install --no-install-recommends feh
apt-get install --no-install-recommends chromium-browser
#apt-get install --no-install-recommends firefox
apt-get install --no-install-recommends xsel
apt-get install --no-install-recommends git
