#!/bin/bash

#exec i3status &

NMON=$(xrandr -d :0 -q | grep ' connected' | wc -l)

if [ "$NMON" = "2" ]; then
  $HOME/bin/dblmon 
fi

#eval `cat $HOME/.fehbg` 
exec feh --bg-scale $HOME/.i3/ak47-181456.png &

#sleep 1

exec i3status

#i3-msg restart &

#do
#    read line
#    LG=$(setxkbmap -print | grep xkb_symbols | awk -F"+" '{print $2}') 
#    echo "LG: $LG | $line" || exit 1
#done
